@startuml
!define RECTANGLE class

RECTANGLE PresentationLayer {
  UniApp
}

RECTANGLE BusinessLogicLayer {
  CloudFunctions
  Server
}

RECTANGLE DataAccessLayer {
  CloudDatabase
}

rectangle "TSYD-OA System" {
  PresentationLayer -- BusinessLogicLayer
  BusinessLogicLayer -- DataAccessLayer
}

@enduml
