@startuml



state 任务状态 {
  [*] --> 创建中
  创建中 --> 进行中 : 创建完成
  创建中 --> 已取消 : 任务取消
}

state 进行中 {

  进行中 --> 完成 : 完成任务
  进行中 --> 已逾期 : 逾期未完成
  进行中 --> 已取消 : 任务取消
}

state 已逾期 {
  已逾期 --> 已取消 : 任务取消
}

state 已取消 {

}

state 完成 {

}


@enduml
