@startuml

!define RECTANGLE class
!define DATABASE database
!define CLOUD cloud

RECTANGLE "系统消息模块" {
  +展示系统消息
  +查看详细内容
}

RECTANGLE "任务模块" {
  +任务创建与分配
  +任务查看和更新
  +任务完成与反馈
}

RECTANGLE "文件模块" {
  +文件上传和下载
  +文件管理
}

RECTANGLE "用户管理模块" {
  +用户登录和退出
  +用户信息管理
  +权限控制
}

RECTANGLE "用户任务管理子系统" {
  "系统消息模块"
  "任务模块"
  "文件模块"
  "用户管理模块"
}

RECTANGLE "后台管理子系统" {
  "系统管理模块"
}

RECTANGLE "系统管理模块" {
    +系统配置
    +系统日志
    +系统监控
}

"用户任务管理子系统" -- "系统消息模块"
"用户任务管理子系统" -- "任务模块"
"用户任务管理子系统" -- "文件模块"
"用户任务管理子系统" -- "用户管理模块"
"后台管理子系统" -- "系统管理模块"

@enduml
